# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary_contents',
            old_name='creater',
            new_name='preparing_person',
        ),
    ]
