# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160805_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary_contents',
            old_name='owner',
            new_name='preparing_person',
        ),
    ]
